### ISSUE TITLE
README reference non existant files

### ISSUE THREAD

**Issue by heckj** [01org/IntelRackScaleArchitecture#2]
Afternoon!

The README.md references the following files that don't appear to exist, and aren't available (that I could find) from the referenced HTML pages and marketecture. Could you point me to where I can find these, and update the README appropriately?

 * PSME Rest API
 * PODM Rest API
 * GAMI API

Thanks!

**Comment by intelrsasw** [comment]
Hello! 
Thank you for your feedback. Yes, expect those documents to go live very soon. I'll close this out when they do so you'll know. We're still propagating all the files. You are a first! I put a note about this in the readme so hopefully people will see that.

Thanks!

Amy Adams 
Intel Corporation
~Technical Program Manager~
Cloud Platform Group – Rack Scale Architecture

**Comment by intelrsasw** [comment]
I have updated the links to the documentation (which is now live). Here is the direct link: http://www.intel.com/content/www/us/en/architecture-and-technology/rack-scale-architecture/intel-rack-scale-architecture-resources.html

Thanks again for your feedback!

Amy
