### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [01org/IntelRackScaleArchitecture#4]
I would like to point out that identifiers like "[`__ASSETD_ATTRIBUTE_H__`](https://github.com/01org/IntelRackScaleArchitecture/blob/39f89bbc5598eb616572b3bf37e77bb9412eccab/RSA-SW/RMM/src/core/assetd/attribute.h#L16)" and "[`_MEMDB_H_`](https://github.com/01org/IntelRackScaleArchitecture/blob/39f89bbc5598eb616572b3bf37e77bb9412eccab/RSA-SW/RMM/src/core/memdbd/memdb.h#L16)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by pperycz-intel-rsa** [comment]
Hello!

Thank you for your feedback! We will review your suggestions and come back with an answer as soon as possible.

Best regards,
Przemyslaw Perycz

**Comment by sdpslfz** [comment]
Hi Elfring:

As the discussion in our development team, we are going to follow the Linux kernel standard instead of the C++ language standard, and we would align them in the next release.
And thanks for your suggestion.

**Comment by elfring** [comment]
Would you like to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by sdpslfz** [comment]
Hi elfring:

We are using Linux running on X86 for the developing environment, and using gcc as the compiler, and we won't encounter the undefined behaviour issue.

**Comment by elfring** [comment]
Would you like to achieve [more standard-compliance](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by intelrsasw** [comment]
Hi Elfring,
Thanks for your feedback again! For now we will continue to use GCC as the compiler using Linux running on x86 and won't be taking this issue at this time. We may consider this issue as we consider newer designs in the future. 
Thanks,
Intel® Rack Scale Architecture Team

**Comment by elfring** [comment]
The chosen C++ compiler variant does not really matter here.
How do you think about to delete any underscores from affected identifiers?

**Comment by sdpslfz** [comment]
Hi Elfring:

Thanks for your feed back again.
As we don't think the underscores would have any affect to the functions or performance, and we are following what people do in the Linux Kernel, so we won't have it changed in the further development.

Thanks
Benima

**Comment by elfring** [comment]
Do you care for [consequences from undefined behaviour](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Debugging-Options.html#index-fsanitize_003dundefined-652 "Checking for undefined behaviour?")?

**Comment by sdpslfz** [comment]
Hi Elfring:

Do you think that adding underscores in identifiers would trigger undefined behaviour?

Thanks
Benima

**Comment by elfring** [comment]
Yes. - Inappropriate identifier selection can result in undefined behaviour.

**Comment by sdpslfz** [comment]
Hi Elfring:

We know that C++( from C++03) is trying to define some rules(or recommendation) for coding style in standard spec., e.g. reserving double underscores or single underscore followed by uppercase, e.g. compiler itself, but clearly it is hard to apply this rule to those project earlier than 2003, e.g. Linux kernel,  we can find the double underscore or single underscore followed uppercase is used everywhere in Linux source tree(kernel or non-kernel code, macro, header, API etc.) as long as their definition won’t conflict with existing definition.
So we are going to list the supported tool chains and building environment for the end user to avoid such kind of issues.

Thanks
Benima

**Comment by elfring** [comment]
Would you like to reduce the tampering with the reserved name space then?
Are you becoming more interested in picking software development challenges up for a corresponding source code clean-up?
